# create volume.
# install drivers.
# grant privilleges for IAM ebs
# create persistentVolume
# create persistentVolumeClaim
# assigning the pvc to pod.

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-03c604538dd7d2f41

