# similar to static provisoners.
# the volume disk is mantained by kuberenetes.

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-dynamic  # from storage class it created.
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: pod
metadata:
  name: ebs-dynamic
  namespace: expense
  labels:
    product: testing
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: ebs-dynamic
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-dynamic
    persistentVolumeClaim:
      claimName: ebs-dynamic
---
apiVersion: v1
kind: service
metadata:
  name: ebs-dynamic
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    product: testing
  ports:
  - name: ebs-dynamic-svc
    protocol: TCP
    port : 80
    targetPort: 80 


# kubectl get pv   --for peristent volume
# kubectl get pvc  --for persistent volume claims
# 