# it is like a vpc, creates an isolated environment.
apiVersion: v1 
kind: Namespace
metadata:
  name: expense
  labels: 
    project: expense
    envirnoment: dev
 
# kubectl apply -f 01-namespace.yaml'
#kubectl describe namespace expense
