apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  containers:
    - name: nginx
      image: nginx
    - name: almalinux
      image: almalinux:9
      command: ["sleep","100"]

#kubectl apply -f 03-multicontainer.yaml
