apiVersion: v1
kind: Pod
metadata:
  name: annotations
  annotations:
    imageregistry: "https://hub.docker.com/"  # lables and annotation are similar but annotation can store more complex values
spec:
  containers:
    - name: nginx
      image: nginx
