apiVersion: v1
kind: Pod
metadata:
  name: resource
  labels:
    app: web-nginx
    project: demo
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:    # soft limit
          memory: "64Mi"
          cpu: "250m"   # 1cpu = 1000m cpu
        limits:         # hard limit
          memory: "120Mi"
          cpu: "400m"

#kubectl apply -f 07-resource-limit.yaml
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    app: web-nginx
    project: demo
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80
