apiVersion: v1
kind: pod
metadata:
  name: pod-config
spec: 
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          valueFrom:
            configMapKeyRef:
              name: nginx-config  # this name is defined in the configmap metadata. 
              key: course
        - name: duration
          valueFrom:
            configMapKeyRef:
              name: nginx-config  # this name is defined in the configmap metadata. 
              key: duration