apiVersion: v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  lables:
    envirnoment: dev
    firm: ReplicaSet
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      project: expense
      envirnoment: dev
      module: demo
  template:
    metadata:
      labels:
        project: expense
        envirnoment: dev
        module: demo
        tier: nginx_replicas
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: service
metadata:
  name: nginx_service
spec:
  selector:
    project: expense
    envirnoment: dev
    module: demo
  ports: 
  - name: nginx-svc-port
    protocol: TCP
    port: 80  # service port
    targetPort: 80  # conatinaer port

