apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    project: demo
    envirnoment: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      project: expense
      envirnoment: dev
      module: demo
  template:
    metadata:
      labels:
        project: expense
        envirnoment: dev
        module: demo
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
  
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  #type: NodePort/LoadBalancer/ClusterIP(default)
  selector:
    project: expense
    envirnoment: dev
    module: demo
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80   # service port 
    targetPort: 80   # conatainer port
